In [3]:
#Import relevant libraries
import astropy
import numpy as np
import ccdproc
import os
import glob
import matplotlib.pyplot as plt
from astropy.nddata import CCDData

In [4]:
#TASK 1
#Here we are calculating the mean and standard deviations of a single bias frame
#We first have to read in the single bias frame using the code below and use numpy to calculate the mean and std
biasImg1 = astropy.nddata.CCDData.read('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/raw/bias/20131220.00000200.bias.fits', unit='adu')
print(biasImg1)
mean1 = np.mean(biasImg1)
stdev1 = np.std(biasImg1)
print(mean1, stdev1)

[[147 125 108 ...  99  99 105]
 [136 121 117 ...  91 121 105]
 [141 116 120 ... 107 105 111]
 ...
 [131 133 123 ... 104 126 120]
 [141 124 124 ...  99 128 124]
 [128 124 125 ... 113 121 109]] adu
111.34115219116211 14.561503353266682


In [9]:
#TASK 2
#Here our aim is to append all the bias images which means we want to combine them all to create a master bias frame
#Create list of bias images

from os import listdir
from os.path import isfile, join
file_location = os.path.join('20191111/', 'bias/', '*.fits')
filenames = glob.glob('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/20191111/bias/*.fits')

biasimages = []
for file in filenames:
    biasImg = astropy.nddata.CCDData.read(file, unit='adu')
    hdul = astropy.nddata.CCDData.to_hdu(biasImg)
    biasimages.append(biasImg)
    #print(np.std(biasImg))
print(biasimages)
print(len(biasimages))
#print(biasimages.shape)

[CCDData([[ 933,  925,  945, ...,  976,  977,  968],
         [ 948,  951,  953, ...,  951,  975,  987],
         [ 956,  939,  938, ...,  966,  981, 1006],
         ...,
         [ 959,  935,  965, ...,  974,  997, 1009],
         [ 949,  966,  945, ...,  979,  996, 1019],
         [ 954,  956,  955, ...,  994,  989, 1011]], unit='adu'), CCDData([[ 965,  947,  947, ...,  986,  988, 1000],
         [ 958,  961,  956, ...,  976,  997, 1009],
         [ 950,  957,  952, ...,  980,  982,  984],
         ...,
         [ 977,  968,  963, ...,  979,  985,  996],
         [ 975,  975,  958, ...,  989, 1014, 1020],
         [ 953,  955,  968, ..., 1001, 1001, 1015]], unit='adu'), CCDData([[ 954,  953,  948, ...,  970,  984,  978],
         [ 958,  949,  959, ...,  970,  981, 1005],
         [ 943,  947,  946, ...,  970,  993,  991],
         ...,
         [ 958,  963,  952, ...,  978,  999, 1008],
         [ 965,  959,  955, ..., 1002, 1006, 1017],
         [ 958,  965,  968, ...,  989, 1012, 

In [4]:
#TASK 2 CONT
#Here we have used the code to combine the bias frames but have hashtagged it out to prevent any memory space issues when running the code

#Combine bias images into master bias
#ccdproc.combine(biasimages, output_file = 'expbias.fits', method = 'median') #median to filter out cosmic rays

In [5]:
#TASK 3

#Here we have calcualted the mean and std of the masterbias using the same code from task 1


masterbias = astropy.nddata.CCDData.read('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/expbias.fits', unit='adu')
biasmean = np.mean(masterbias)
biasstdev = np.std(masterbias)
print(biasmean, biasstdev)

INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
961.5345392525196 5.07012004929655


In [6]:
#TASK 4
#We now obtain dark frames from a separate project but still apply it to our project.
#In this section of the code we are combining all of the dark frames to create a master dark 

#Create list of dark frames
file_location = os.path.join('Ekard/', 'dark/', '*.fits')

filenames = glob.glob('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/Ekard/darks/*.fits')
darkimages = []
for file in filenames:
    darkImg = astropy.nddata.CCDData.read(file, unit='adu')
    hdul = astropy.nddata.CCDData.to_hdu(darkImg)
    darkSub = darkImg.subtract(masterbias)
    darkimages.append(darkSub)

print(darkimages)

[CCDData([[ 10. ,  11.5,  21.5, ...,   5. ,  -6.5,  23. ],
         [  5.5,  15. ,   4.5, ...,  14.5,   7. ,  -1. ],
         [ -2.5,  24. ,  11. , ...,   7. ,   8.5,   7.5],
         ...,
         [  8.5,  -4. ,   5. , ...,  11. ,  16.5,  16.5],
         [ -5.5,  -1. ,   3.5, ...,  13. , -14.5,  16. ],
         [  9.5,  26. ,   0.5, ...,   6. ,   4. ,   3. ]], unit='adu'), CCDData([[26. ,  6.5, 13.5, ..., 10. ,  7.5,  1. ],
         [ 4.5,  0. ,  6.5, ..., -8.5,  1. ,  3. ],
         [ 7.5, 19. , 26. , ..., 11. , 17.5,  3.5],
         ...,
         [-5.5,  1. ,  8. , ...,  9. , 11.5, 11.5],
         [17.5, -3. , -9.5, ...,  3. , -2.5,  6. ],
         [12.5, 14. , -1.5, ..., -3. ,  4. ,  9. ]], unit='adu'), CCDData([[ -4. ,  10.5,  20.5, ...,   6. ,  -5.5,  24. ],
         [ 15.5,  -2. ,  11.5, ...,   7.5,  -3. ,   7. ],
         [ 17.5,  -6. ,  16. , ...,  24. ,  -8.5,  -2.5],
         ...,
         [-10.5,  -4. ,  -6. , ...,   5. ,  24.5,  20.5],
         [  0.5, -10. ,  -4.5, ...,  

In [7]:
#TASK 4 CONT
#To ensure that we can use the dark frame in the correction of the science frame we have to ensure the exposure times are the same
#Check whether exposure time of dark frame = exposure time of science

#We read in a single science frame for the B and V band and compare the exposure times to that of the dark frame
ScienceImgB = astropy.nddata.CCDData.read('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/Science_B/20191111.00000030.fits', unit='adu')
ScienceImgV = astropy.nddata.CCDData.read('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/Science_V/20191111.00000055.fits', unit='adu')

print(darkImg[1].header['EXPTIME'])
print(ScienceImgB[1].header['EXPTIME'])
print(ScienceImgV[1].header['EXPTIME'])


30.0
60.0
60.0


In [9]:
#TASK 4  CONT
#We know have to combine the master dark and then correct the master dark to account for the difference in exposure time
#ccdproc.combine(darkimages, output_file = 'expbias.fits', method = 'median')


masterdark = astropy.nddata.CCDData.read('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/expmasterdark.fits', unit='adu')

masterdark = masterdark.multiply(2)
print(masterdark)
hdul = astropy.nddata.CCDData.to_hdu(masterdark)
hdul.writeto('expdark.fits', overwrite=True)

INFO: using the unit adu passed to the FITS reader instead of the unit adu in the FITS file. [astropy.nddata.ccddata]
[[21.42857143 25.57142857 34.42857143 ... 16.28571429  7.
  24.28571429]
 [13.57142857 23.14285714  8.71428571 ...  1.57142857 -3.42857143
  10.85714286]
 [16.42857143 12.28571429 24.85714286 ... 25.14285714  5.28571429
  14.71428571]
 ...
 [-4.14285714  7.14285714  7.42857143 ... 22.28571429 22.14285714
  18.71428571]
 [ 3.28571429 -2.28571429 13.57142857 ... 10.28571429 -4.42857143
   8.57142857]
 [11.85714286 13.42857143  2.71428571 ...  2.85714286  3.14285714
   8.        ]] adu


In [10]:
#TASK 5
#Mean and Standard Deviation of master dark as shown in Task 1

darkmean = np.mean(masterdark)
darkstdev = np.std(masterdark)
print(darkmean, darkstdev)

11.494906570230217 104.5316214806753


In [11]:
#TASK 6
#Here we subtract our master bias and master dark from our flat frames for both the B and V optical filter band
#We then normalise it toa pixel count of unity by dividing by the mean of the flat frame


file_location = os.path.join('GlobularClusters/', 'flat_B/', '*.fits')
filenames = glob.glob('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/flat_B/*.fits')
flatsimagesB = []
normflatsimagesB = []
for file in filenames:
    flatImg = astropy.nddata.CCDData.read(file, unit='adu')
    hdul = astropy.nddata.CCDData.to_hdu(flatImg)
    flatSub1 = flatImg.subtract(masterbias)
    flatSub2 = flatSub1.subtract(masterdark)
    flatmean = np.mean(flatSub2)
    normalised = flatImg.divide(flatmean)
    flatsimagesB.append(flatSub2)
    normflatsimagesB.append(normalised)
print(flatsimagesB)
print(normflatsimagesB)

[CCDData([[19649.57142857, 19325.92857143, 19423.07142857, ...,
          19503.71428571, 19711.5       ,    98.71428571],
         [18960.92857143, 19505.85714286, 19128.78571429, ...,
          19273.92857143, 19919.42857143,   105.14285714],
         [19129.07142857, 19332.71428571, 19559.14285714, ...,
          18787.85714286, 19610.21428571,    52.78571429],
         ...,
         [19233.64285714, 19088.85714286, 18831.57142857, ...,
          19235.71428571, 19503.35714286,    50.78571429],
         [18978.21428571, 19203.28571429, 19082.92857143, ...,
          19715.71428571, 20097.92857143,    73.42857143],
         [19255.64285714, 18852.57142857, 19317.78571429, ...,
          19625.14285714, 20072.85714286,   104.        ]], unit='adu'), CCDData([[21786.57142857, 21553.92857143, 21327.07142857, ...,
          21557.71428571, 21796.5       ,   103.71428571],
         [21408.92857143, 21529.85714286, 21040.78571429, ...,
          21233.92857143, 22001.42857143,   122.142857

In [12]:
#TASK 6 CONT
file_location = os.path.join('GlobularClusters/', 'flat_V/', '*.fits')
filenames = glob.glob('C:/Users/steve/OneDrive - University of Birmingham/LH Observatory Laboratory/Glob Cluter Final Code/GlobClusters/flat_V/*.fits')
flatsimagesV = []
normflatsimagesV = []
for file in filenames:
    flatImg = astropy.nddata.CCDData.read(file, unit='adu')
    hdul = astropy.nddata.CCDData.to_hdu(flatImg)
    flatSub1 = flatImg.subtract(masterbias)
    flatSub2 = flatSub1.subtract(masterdark)
    flatmean = np.mean(flatSub2)
    normalised = flatImg.divide(flatmean)
    flatsimagesV.append(flatSub2)
    normflatsimagesV.append(normalised)
print(flatsimagesV)
print(normflatsimagesV)

[CCDData([[15347.57142857, 15489.92857143, 15178.07142857, ...,
          15776.71428571, 15696.5       ,   253.71428571],
         [15271.92857143, 15260.85714286, 15356.78571429, ...,
          15300.92857143, 15812.42857143,   269.14285714],
         [15226.07142857, 15294.71428571, 15430.14285714, ...,
          15295.85714286, 15517.21428571,   281.78571429],
         ...,
         [15268.64285714, 15323.85714286, 15086.57142857, ...,
          15484.71428571, 15821.35714286,   261.78571429],
         [15106.21428571, 15634.28571429, 15226.92857143, ...,
          15668.71428571, 15815.92857143,   242.42857143],
         [15489.64285714, 15339.57142857, 15372.78571429, ...,
          15691.14285714, 15942.85714286,   260.        ]], unit='adu'), CCDData([[13964.57142857, 14028.92857143, 13827.07142857, ...,
          14238.71428571, 14239.5       ,   229.71428571],
         [13682.92857143, 13825.85714286, 13878.78571429, ...,
          13942.92857143, 14407.42857143,   244.142857

In [13]:
#TASK 7
#Here we combine the flat frames to create a master flat in B and a master flat in V
#ccdproc.combine(normflatsimagesB, output_file = 'expflatB.fits')
#ccdproc.combine(normflatsimagesV, output_file = 'expflatV.fits')